# Generated by Django 4.2.7 on 2023-12-31 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after_transactions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[(1, 'Deposite'), (2, 'Withdrawl'), (3, 'Loan'), (4, 'Loan Paid')], max_length=17)),
                ('time_stamped', models.DateTimeField(auto_now_add=True)),
                ('loan_aproval', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userbankaccountmodel')),
            ],
            options={
                'ordering': ['time_stamped'],
            },
        ),
    ]
